[build]
  base = "backend"  # Set the base directory to "backend"

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"


[context.production]
  command = "npm run build:production" # Customize for your production build if needed
